# -*- coding: utf-8 -*-
"""بسم الله الرحمن الرحيم PSD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mQiDJuBxY-LXlmsBzZGFYx_PvcwVEo7
"""

# --- CELL 1: IMPORT LIBRARY ---

# Pandas untuk mengolah data tabel (seperti Excel)
import pandas as pd

# Json untuk membaca file peta (GeoJSON)
import json

# Folium untuk membuat peta interaktif
import folium

# Copy untuk menduplikasi data agar data asli tidak rusak
import copy

# Scikit-Learn untuk Kecerdasan Buatan (Machine Learning)
# StandardScaler: Untuk menyamakan skala angka (agar data kecil tidak kalah dengan data besar)
from sklearn.preprocessing import StandardScaler
# KMeans: Algoritma untuk mengelompokkan data (Clustering)
from sklearn.cluster import KMeans

# Ipywidgets untuk membuat tombol interaktif (Dropdown menu)
from ipywidgets import Dropdown, VBox, Output, HTML
# IPython.display untuk menampilkan hasil HTML cantik di layar
from IPython.display import display, HTML as IPyHTML

# --- CELL 2: LOAD & CLEANING DATA ---

try:
    # 1. Membaca file CSV data HIV
    df = pd.read_csv('jumlah_kasus_hiv_berdasarkan_kelompok_umur_v1_data.csv')

    # 2. Membaca file Peta Jawa Barat (GeoJSON)
    with open('jawa_barat_32_batas_kabkota.geojson', 'r') as f:
        geo_data_raw = json.load(f)

    # 3. Membersihkan Data
    # Mengubah kolom 'jumlah_kasus' jadi angka. Jika ada error, ubah jadi 0.
    df['jumlah_kasus'] = pd.to_numeric(df['jumlah_kasus'], errors='coerce').fillna(0)

    # Merapikan nama kota (Huruf Besar Awal) agar cocok dengan peta
    df['nama_kabupaten_kota'] = df['nama_kabupaten_kota'].str.title()

    # Menyeragamkan penulisan Gender jadi HURUF KAPITAL
    df['jenis_kelamin'] = df['jenis_kelamin'].str.upper()

    # 4. Membuat Kategori Umur Sederhana
    # Fungsi ini mengelompokkan umur yang detail menjadi 4 kelompok besar
    def simple_cat(x):
        if x in ['0-4', '5-14']: return 'Anak-anak'
        elif x in ['15-19', '20-24']: return 'Remaja'
        elif x in ['25-49']: return 'Dewasa'
        else: return 'Lansia'

    # Terapkan fungsi di atas ke kolom 'kelompok_umur'
    df['kategori_simple'] = df['kelompok_umur'].apply(simple_cat)

    print("✅ Data berhasil dimuat dan dibersihkan.")

except Exception as e:
    # Jika file tidak ditemukan atau error, tampilkan pesan error
    print(f"❌ Error: {e}")

# --- CELL 3: FUNGSI AI CLUSTERING ---

def get_ai_clusters(df_input):
    # Jika data kosong, kembalikan hasil kosong
    if df_input.empty: return {}, {}, {}

    # 1. Pivot Table: Ubah data jadi bentuk matriks (Baris: Kota, Kolom: Umur)
    # Ini agar AI bisa melihat pola persebaran umur di tiap kota
    df_p = df_input.pivot_table(index='nama_kabupaten_kota', columns='kategori_simple', values='jumlah_kasus', aggfunc='sum', fill_value=0)

    # Syarat AI: Minimal butuh 3 kota untuk bisa membagi 3 kelompok
    if len(df_p) < 3: return {}, {}, {}

    # 2. Normalisasi Data
    scaler = StandardScaler()
    X = scaler.fit_transform(df_p) # Ubah angka jadi skala standar (-1 s/d 1)

    # 3. Proses Clustering (K-Means)
    # Membagi kota menjadi 3 kelompok berdasarkan kemiripan pola data
    km = KMeans(n_clusters=3, random_state=42, n_init=10)
    df_p['cluster'] = km.fit_predict(X)
    df_p['total'] = df_p.sum(axis=1) # Hitung total kasus untuk ranking

    # 4. Mengurutkan Cluster (Ranking)
    # Kita urutkan supaya Cluster 0 = Kasus Rendah, Cluster 2 = Kasus Tinggi
    rank = df_p.groupby('cluster')['total'].mean().sort_values().index

    # 5. Definisi Warna & Label (Sesuai Opsi 1: Risiko Rendah)
    cmap = {
        rank[0]: {'c':'#2ecc71', 'lbl':'ZONA HIJAU', 'desc':'Risiko Rendah', 'score': 1},   # Score 1 = Aman
        rank[1]: {'c':'#f1c40f', 'lbl':'ZONA KUNING', 'desc':'Waspada / Sedang', 'score': 2},# Score 2 = Waspada
        rank[2]: {'c':'#e74c3c', 'lbl':'ZONA MERAH', 'desc':'Bahaya / Tinggi', 'score': 3}   # Score 3 = Bahaya
    }

    # 6. Simpan hasil ke dictionary untuk dipakai peta
    colors, labels, city_scores = {}, {}, {}
    for kota, row in df_p.iterrows():
        clust_id = row['cluster']
        colors[kota] = cmap[clust_id]['c']      # Warna Peta
        labels[kota] = cmap[clust_id]           # Label Teks
        city_scores[kota] = cmap[clust_id]['score'] # Skor Angka (1-3)

    return colors, labels, city_scores

# --- CELL 4: LOGIKA STATUS PROVINSI ---

def calculate_province_status(df_filtered, city_scores):
    # Hitung total kasus per kota
    kota_totals = df_filtered.groupby('nama_kabupaten_kota')['jumlah_kasus'].sum()
    total_kasus_provinsi = kota_totals.sum()

    # Jika tidak ada kasus sama sekali
    if total_kasus_provinsi == 0:
        return {'lbl':'ZONA HIJAU', 'desc':'Tidak Ada Kasus', 'c':'#2ecc71'}

    # RUMUS: Weighted Risk Score (Skor Risiko Tertimbang)
    # Skor Kota (1/2/3) dikalikan jumlah kasusnya.
    # Tujuannya: Kota dengan kasus banyak punya pengaruh lebih besar ke status provinsi.
    weighted_score = 0
    for kota, total in kota_totals.items():
        score = city_scores.get(kota, 1) # Default score 1 jika data kota hilang
        weighted_score += (score * total)

    # Mencari Rata-rata Risiko (Hasilnya angka antara 1.0 sampai 3.0)
    avg_risk_index = weighted_score / total_kasus_provinsi

    # Menentukan Status berdasarkan Indeks Risiko
    if avg_risk_index >= 2.2:
        return {'lbl':'ZONA MERAH', 'desc':'Bahaya (Dominasi Klaster Tinggi)', 'c':'#e74c3c'}
    elif avg_risk_index >= 1.6:
        return {'lbl':'ZONA KUNING', 'desc':'Waspada (Sebaran Meningkat)', 'c':'#f1c40f'}
    else:
        # Menggunakan istilah "Risiko Rendah"
        return {'lbl':'ZONA HIJAU', 'desc':'Risiko Rendah (Dominasi Klaster Rendah)', 'c':'#2ecc71'}

# --- CELL 5: GENERATOR REKOMENDASI ---

def get_policy_advice(zona_label, data_usia, filter_gender):
    advice = []

    # A. Saran Berdasarkan ZONA
    if zona_label == 'ZONA MERAH':
        advice.append("<b>🚨 DARURAT PROVINSI:</b> Eskalasi kasus tinggi. Gubernur perlu menginstruksikan penambahan anggaran darurat HIV dan audit stok obat ARV di seluruh RSUD.")
        advice.append("<b>🏥 FASKES:</b> Wajibkan skrining HIV bagi seluruh pasien rawat inap dengan gejala oportunistik di RS Rujukan.")
    elif zona_label == 'ZONA KUNING':
        advice.append("<b>⚠️ PERINGATAN DINI:</b> Tren kasus meningkat. Perkuat peran Dinkes Provinsi untuk supervisi daerah dengan kasus tinggi.")
        advice.append("<b>📢 KAMPANYE:</b> Gencarkan sosialisasi masif melalui media sosial dan tokoh masyarakat tingkat provinsi.")
    else: # ZONA HIJAU (RISIKO RENDAH)
        advice.append("<b>✅ MONITORING:</b> Pertahankan kondisi risiko rendah. Fokuskan anggaran pada edukasi preventif untuk mencegah lonjakan kasus.")

    # B. Saran Berdasarkan KELOMPOK UMUR
    if data_usia['Anak-anak'] > 0:
        advice.append("<b>👶 IBU & ANAK:</b> Prioritas penyelamatan generasi. Audit pelaksanaan 'Triple Eliminasi' pada Ibu Hamil di seluruh Puskesmas.")
    if data_usia['Remaja'] > 50:
        advice.append("<b>🎓 REMAJA:</b> Kasus muda tinggi. Disdik Provinsi wajib memasukkan modul kesehatan reproduksi di SMA/SMK.")

    # C. Saran Berdasarkan GENDER
    if filter_gender == 'LAKI-LAKI':
        advice.append("<b>♂️ LAKI-LAKI:</b> Fokus pada komunitas pekerja dan bapak rumah tangga. Libatkan Serikat Pekerja untuk sosialisasi.")
    elif filter_gender == 'PEREMPUAN':
        advice.append("<b>♀️ PEREMPUAN:</b> Fokus perlindungan Ibu Rumah Tangga. Optimalkan peran PKK dan Posyandu untuk deteksi dini.")

    return advice

# --- CELL 6: VISUALISASI UTAMA & INTERAKTIVITAS ---

# 1. Membuat Pilihan Menu Dropdown
opt_th = ['SEMUA TAHUN'] + sorted(df['tahun'].unique(), reverse=True)
opt_jk = ['SEMUA GENDER'] + sorted(df['jenis_kelamin'].unique().tolist())
opt_kt = ['SEMUA KAB/KOTA'] + sorted(df['nama_kabupaten_kota'].unique())

w_th = Dropdown(options=opt_th, description='📅 Tahun:')
w_jk = Dropdown(options=opt_jk, description='👥 Gender:')
w_kt = Dropdown(options=opt_kt, description='📍 Highlight:')
out_view = Output() # Wadah untuk menampilkan hasil

# HTML Legend (Keterangan Warna Peta) - Updated: Risiko Rendah
legend_html = '''
<div style="position: fixed; bottom: 30px; left: 30px; z-index:9999; font-size:12px;
background:white; padding: 10px; border:1px solid grey; opacity:0.9; box-shadow: 2px 2px 5px grey; border-radius:5px;">
<b>ZONA RISIKO (AI)</b><br>
<span style="color:#e74c3c;">■</span> Merah (Bahaya)<br>
<span style="color:#f1c40f;">■</span> Kuning (Waspada)<br>
<span style="color:#2ecc71;">■</span> Hijau (Risiko Rendah)
</div>
'''

# 2. Fungsi Utama: Dijalankan setiap kali user mengganti pilihan menu
def update_view(change=None):
    out_view.clear_output(wait=True) # Hapus tampilan lama
    th, jk, kt = w_th.value, w_jk.value, w_kt.value # Ambil nilai dari dropdown

    # --- PROSES FILTER DATA ---
    df_f = df.copy()
    if th != 'SEMUA TAHUN': df_f = df_f[df_f['tahun'] == th]
    if jk != 'SEMUA GENDER': df_f = df_f[df_f['jenis_kelamin'] == jk]

    # --- JALANKAN AI CLUSTERING ---
    colors, labels_data, city_scores = get_ai_clusters(df_f)

    # Hitung total dan detail per umur untuk keperluan tabel
    df_grp = df_f.groupby('nama_kabupaten_kota')['jumlah_kasus'].sum()
    df_det = df_f.pivot_table(index='nama_kabupaten_kota', columns='kategori_simple', values='jumlah_kasus', aggfunc='sum', fill_value=0)
    for c in ['Anak-anak', 'Remaja', 'Dewasa', 'Lansia']:
        if c not in df_det.columns: df_det[c] = 0

    # --- SIAPKAN PETA (FOLIUM) ---
    geo_current = copy.deepcopy(geo_data_raw)

    # Loop setiap kota di peta untuk diberi warna & info
    for feature in geo_current['features']:
        kota = feature['properties']['name'].title()
        tot = df_grp.get(kota, 0)
        risk_info = labels_data.get(kota, {'lbl':'N/A', 'desc':''})

        # Siapkan Data Tabel Kecil untuk Popup di Peta
        r = df_det.loc[kota] if kota in df_det.index else pd.Series({'Anak-anak':0, 'Remaja':0, 'Dewasa':0, 'Lansia':0})
        tbl_popup = f"""
        <table style="width:100%; font-size:10px; border-collapse: collapse;">
            <tr><td>Anak</td><td align="right"><b>{r['Anak-anak']}</b></td></tr>
            <tr><td>Remaja</td><td align="right"><b>{r['Remaja']}</b></td></tr>
            <tr><td>Dewasa</td><td align="right"><b>{r['Dewasa']}</b></td></tr>
            <tr><td>Lansia</td><td align="right"><b>{r['Lansia']}</b></td></tr>
        </table>"""

        # Masukkan info ke dalam properti GeoJSON
        feature['properties']['fillColor'] = colors.get(kota, '#95a5a6') # Warna default abu-abu
        feature['properties']['info_filter'] = f"{th} | {jk}"
        feature['properties']['total_display'] = f"{tot:,.0f}"
        feature['properties']['risk_display'] = f"{risk_info.get('lbl')} ({risk_info.get('desc')})"
        feature['properties']['popup_content'] = f"<div style='width:160px'><b>{kota.upper()}</b><br>{risk_info.get('lbl')}<br>Total: {tot}<hr>{tbl_popup}</div>"

    # Style Peta: Membuat highlight CYAN tebal jika kota dipilih
    def style_function_dynamic(feature):
        kota_name = feature['properties']['name'].title()
        base = feature['properties']['fillColor']
        if kt != 'SEMUA KAB/KOTA' and kota_name.upper() == kt.upper():
            return {'fillColor': base, 'color': 'cyan', 'weight': 4, 'fillOpacity': 0.9, 'opacity': 1}
        return {'fillColor': base, 'color': 'white', 'weight': 1, 'fillOpacity': 0.7, 'opacity': 1}

    # Render Peta
    sw, ne = [-8.0, 106.0], [-5.5, 109.0] # Batas koordinat Jawa Barat
    m = folium.Map(location=[-6.9175, 107.6191], zoom_start=8, min_zoom=8, max_zoom=10, max_bounds=True, min_lat=sw[0], max_lat=ne[0], min_lon=sw[1], max_lon=ne[1], tiles='CartoDB positron')
    m.fit_bounds([sw, ne])
    m.get_root().html.add_child(folium.Element(legend_html)) # Tambah legenda pojok kiri bawah

    # Tooltip (Info saat mouse hover)
    tooltip = folium.GeoJsonTooltip(fields=['name','info_filter','risk_display','total_display'], aliases=['Wilayah:','Filter:','Status:','Total:'], style="background:white; color:#333; padding:10px; border-radius:5px;")
    gj = folium.GeoJson(geo_current, style_function=style_function_dynamic, tooltip=tooltip).add_to(m)
    for f in geo_current['features']: folium.Popup(f['properties']['popup_content'], max_width=250).add_to(gj)

    # --- SIAPKAN LAPORAN HTML (REPORT CARD) ---

    # Logika Header Laporan (Apakah Provinsi atau Kota Spesifik)
    if kt == 'SEMUA KAB/KOTA':
        judul_lap = "JAWA BARAT (PROVINSI)"
        prov_status = calculate_province_status(df_f, city_scores) # Hitung Status Provinsi
        zona_stats = prov_status
        tot_val = df_f['jumlah_kasus'].sum()
        r = df_f.pivot_table(columns='kategori_simple', values='jumlah_kasus', aggfunc='sum').iloc[0] if not df_f.empty else pd.Series()
        det_val = {k: r.get(k, 0) for k in ['Anak-anak','Remaja','Dewasa','Lansia']}
        warna_header = prov_status['c']
    else:
        judul_lap = kt.upper()
        zona_stats = labels_data.get(kt.title(), {'lbl':'N/A', 'desc':''})
        tot_val = df_grp.get(kt.title(), 0)
        r = df_det.loc[kt.title()] if kt.title() in df_det.index else pd.Series({'Anak-anak':0, 'Remaja':0, 'Dewasa':0, 'Lansia':0})
        det_val = r.to_dict()
        warna_header = colors.get(kt.title(), "#95a5a6")

    # Ambil Teks Rekomendasi
    rekomendasi = get_policy_advice(zona_stats.get('lbl'), det_val, jk)
    html_rekomendasi = "<ul style='margin:0; padding-left:20px;'>"
    for r in rekomendasi: html_rekomendasi += f"<li style='margin-bottom:8px;'>{r}</li>"
    html_rekomendasi += "</ul>"

    # HTML Tabel Umur
    html_table = f"""
    <table style="width:100%; border-collapse: collapse; font-family: Arial; font-size: 13px; margin-top:10px;">
        <tr style="background-color: #f1f2f6; color: #333;">
            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">KELOMPOK USIA</th>
            <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">JUMLAH KASUS</th>
        </tr>
        <tr><td style="border: 1px solid #ddd; padding: 8px;">Anak-anak</td><td style="border: 1px solid #ddd; padding: 8px; text-align: right;">{det_val['Anak-anak']:,.0f}</td></tr>
        <tr><td style="border: 1px solid #ddd; padding: 8px;">Remaja</td><td style="border: 1px solid #ddd; padding: 8px; text-align: right;">{det_val['Remaja']:,.0f}</td></tr>
        <tr><td style="border: 1px solid #ddd; padding: 8px;">Dewasa</td><td style="border: 1px solid #ddd; padding: 8px; text-align: right;">{det_val['Dewasa']:,.0f}</td></tr>
        <tr><td style="border: 1px solid #ddd; padding: 8px;">Lansia</td><td style="border: 1px solid #ddd; padding: 8px; text-align: right;">{det_val['Lansia']:,.0f}</td></tr>
    </table>"""

    # HTML Top 5 Wilayah (Hanya muncul jika pilih SEMUA KAB/KOTA)
    html_top5 = ""
    if kt == 'SEMUA KAB/KOTA':
        top5 = df_grp.sort_values(ascending=False).head(5)
        rows = ""
        max_v = top5.max() if not top5.empty else 1
        for c, v in top5.items():
            pct = (v/max_v)*100
            rows += f"<tr><td style='padding:5px; border-bottom:1px solid #eee;'>{c}</td><td style='padding:5px; text-align:right; border-bottom:1px solid #eee;'><b>{v}</b></td><td style='padding:5px; width:40%; border-bottom:1px solid #eee;'><div style='background:#3498db; width:{pct}%; height:8px; border-radius:4px;'></div></td></tr>"
        html_top5 = f"<div style='margin-top:20px; border:1px solid #ddd; padding:10px; border-radius:5px;'><b style='color:#555;'>🏆 5 WILAYAH TERTINGGI</b><table style='width:100%; font-size:12px; margin-top:5px; border-collapse:collapse;'>{rows}</table></div>"

    # HTML Final Layout (Menggabungkan Peta, Header, Tabel, dan Rekomendasi)
    final_html = f"""
    <div style="font-family: Arial, sans-serif; color:#333; max-width: 800px;">
        <div style="background-color: {warna_header}; color: white; padding: 15px; border-radius: 8px 8px 0 0;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <div>
                    <h3 style="margin:0;">📊 LAPORAN: {judul_lap}</h3>
                    <div style="font-size:13px; margin-top:5px; opacity:0.9;">FILTER GENDER: <b>{jk}</b></div>
                </div>
                <div style="text-align:right;">
                    <div style="font-size:11px; text-transform:uppercase; opacity:0.8;">STATUS RISIKO</div>
                    <div style="font-size:18px; font-weight:bold;">{zona_stats.get('lbl')}</div>
                    <div style="font-size:11px;">{zona_stats.get('desc')}</div>
                </div>
            </div>
            <hr style="border:0; border-top:1px solid rgba(255,255,255,0.3); margin:10px 0;">
            <div style="font-size:14px;">TOTAL KASUS: <b style="font-size:16px;">{tot_val:,.0f}</b> ORANG</div>
        </div>
        <div style="border: 1px solid #ddd; border-top:none; padding: 20px; border-radius: 0 0 8px 8px; background-color:white;">
            <div style="display: flex; gap: 20px; flex-wrap: wrap;">
                <div style="flex: 1; min-width: 250px;">
                    <b style="color:#555; display:block; border-bottom:2px solid #eee; padding-bottom:5px;">📋 DATA DEMOGRAFI</b>
                    {html_table}
                    {html_top5}
                </div>
                <div style="flex: 1; min-width: 250px;">
                    <div style="background-color: #fff8e1; border-left: 5px solid #f1c40f; padding: 15px; border-radius: 4px;">
                        <b style="color:#d35400; display:block; margin-bottom:10px;">💡 REKOMENDASI KEBIJAKAN</b>
                        <div style="font-size: 13px; line-height: 1.5;">{html_rekomendasi}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    """

    # Tampilkan Peta dan HTML Laporan
    with out_view: display(m, IPyHTML(final_html))

# Pasang "Sensor" agar fungsi update_view jalan saat menu diubah
w_th.observe(update_view, names='value')
w_jk.observe(update_view, names='value')
w_kt.observe(update_view, names='value')

# Tampilkan Widget dan Output Awal
display(VBox([w_th, w_jk, w_kt]))
display(out_view)
update_view()









